<?php 
$this->content->template['message']['plugin']['plugincreator']['infotext'] = "El plugin Plugin Creator puede crear, editar, reinstalar y desinstalar plugins. Si se trata de crear un plugin, crea la estructura de directorios, crea y rellena el archivo XML con todos los datos posibles, crea las plantillas (en la medida de lo previsible) necesarias, los archivos SQL, el archivo css, el archivo php y los rellena con la clase, y los archivos de mensajes. Al editar, se borran, por ejemplo, las entradas de los módulos en el archivo XML, y para las entradas de la base de datos, las entradas en los archivos de instalación y desinstalación SQL."; 
$this->content->template['message']['plugin']['plugincreator']['create_backend_expl'] = "Aquí puede crear o, en su caso, editar un plugin. Haga clic en \"Guardar\" y se creará la estructura de directorios, incluidos los archivos, hasta donde lo permitan sus especificaciones."; 
$this->content->template['message']['plugin']['plugincreator']['create_backend_menu_annotation'] = "<p>Nota: Se creará automáticamente un elemento de menú con el nombre de su plugin. Aquí sólo puede añadir o modificar elementos del submenú.</p>"; 
$this->content->template['message']['plugin']['plugincreator']['loeschenFrage'] = "¿Borrar el plugin incluyendo la estructura del directorio realmente?"; 
$this->content->template['message']['plugin']['plugincreator']['achtungLoeschen'] = "ATENCIÓN: ¡Este paso no tiene marcha atrás!"; 
$this->content->template['message']['plugin']['plugincreator']['deinstallLink'] = "Si sólo quiere desinstalar el plugin, haga clic aquí"; 
$this->content->template['message']['plugin']['plugincreator']['checkboxCheck'] = "Sí, estoy seguro de que quiero eliminar este plugin de forma irrevocable."; 
$this->content->template['message']['plugin']['plugincreator']['rapid_dev_popup_info'] = "Aquí se puede armar un formulario con elementos de control simples. Seleccione un nombre para la variable y la etiqueta, el tipo de elemento del formulario y, para ciertos tipos de elementos, las respectivas entradas que debe tener el elemento y haga clic en \"Introducir en la base de datos\". Los elementos introducidos de esta manera pueden requerir 2 actualizaciones de la página para ser visibles.
Los datos introducidos en el formulario creado se introducirán en una tabla creada automáticamente. Estos datos se mostrarán automáticamente en una tabla debajo del formulario \"crear nuevos campos\". Si no desea que se muestren los elementos \"crear nuevos campos\" y \"datos de demostración\", elimínelos de la plantilla o desinstale el plugin \"creador de plugins\"."; 

 ?>