<?php 
$this->content->template['message']['plugin']['plugincreator']['infotext'] = "De Plugin Creator plugin kan plugins maken, bewerken, herinstalleren en verwijderen. Als hij een plugin moet maken, maakt hij de directory-structuur aan, maakt en vult het XML-bestand met zoveel mogelijk gegevens, maakt de (voor zover te voorziene) noodzakelijke templates, de SQL-bestanden, het css-bestand, het php-bestand en vult deze met de class, en de berichtenbestanden. Bij het bewerken worden bijv. de modulegegevens in het XML-bestand gewist, voor de databasegegevens de gegevens in de SQL-installatie- en de-installatiebestanden."; 
$this->content->template['message']['plugin']['plugincreator']['create_backend_expl'] = "Hier kunt u een plugin aanmaken of - indien van toepassing - bewerken. Klik op opslaan, de directory-structuur inclusief bestanden - voor zover uw specificaties dat toelaten - zal worden aangemaakt."; 
$this->content->template['message']['plugin']['plugincreator']['create_backend_menu_annotation'] = "<p>Opmerking: Een menu item met de naam van uw plugin zal automatisch worden aangemaakt. Hier kunt u alleen submenu-items toevoegen of wijzigen.</p>"; 
$this->content->template['message']['plugin']['plugincreator']['loeschenFrage'] = "Delete plugin incl. directory structuur echt?"; 
$this->content->template['message']['plugin']['plugincreator']['achtungLoeschen'] = "ATTENTIE: Deze stap kan niet worden teruggedraaid!"; 
$this->content->template['message']['plugin']['plugincreator']['deinstallLink'] = "Als u alleen de plugin wilt verwijderen klik dan hier"; 
$this->content->template['message']['plugin']['plugincreator']['checkboxCheck'] = "Ja, ik ben er zeker van dat ik deze plugin onherroepelijk wil verwijderen."; 
$this->content->template['message']['plugin']['plugincreator']['rapid_dev_popup_info'] = "Hier kunt u een formulier samenstellen met eenvoudige besturingselementen. Kies een naam voor de variabele en het label, het type formulierelement, en voor bepaalde elementtypes de respectieve vermeldingen die het element moet hebben en klik op \"In database invoeren\". Elementen die op deze manier zijn ingevoerd kunnen 2 pagina verversingen nodig hebben om zichtbaar te worden.
Gegevens die in het aangemaakte formulier worden ingevoerd, zullen in een automatisch aangemaakte tabel worden ingevoerd. Deze gegevens zullen dan automatisch worden weergegeven in een tabel onder het formulier \"nieuwe velden aanmaken\". Als je niet wilt dat de elementen \"nieuwe velden aanmaken\" en \"demo gegevens\" worden weergegeven, verwijder ze dan uit het sjabloon of verwijder de \"plugin creator\" plugin."; 

 ?>