<?php 
$this->content->template['message']['plugin']['plugincreator']['infotext'] = "Le plugin Plugin Creator permet de créer, modifier, réinstaller et désinstaller des plugins. S'il s'agit de créer un plugin, il crée la structure du répertoire, crée et remplit le fichier XML avec autant de données que possible, crée les modèles nécessaires (dans la mesure du possible), les fichiers SQL, le fichier css, le fichier php et les remplit avec la classe, et les fichiers de messages. Lors de l'édition, les entrées du module dans le fichier XML sont supprimées, pour les entrées de la base de données, les entrées dans les fichiers SQL d'installation et de désinstallation."; 
$this->content->template['message']['plugin']['plugincreator']['create_backend_expl'] = "Ici, vous pouvez créer ou - le cas échéant - modifier un plugin. Cliquez sur enregistrer, la structure du répertoire comprenant les fichiers - dans la mesure où vos spécifications le permettent - sera créée."; 
$this->content->template['message']['plugin']['plugincreator']['create_backend_menu_annotation'] = "<p>Remarque : un élément de menu portant le nom de votre plugin sera créé automatiquement. Ici, vous pouvez uniquement ajouter ou modifier des éléments de sous-menu.</p>"; 
$this->content->template['message']['plugin']['plugincreator']['loeschenFrage'] = "Supprimer le plugin y compris la structure du répertoire vraiment ?"; 
$this->content->template['message']['plugin']['plugincreator']['achtungLoeschen'] = "ATTENTION : Cette étape ne peut pas être inversée !"; 
$this->content->template['message']['plugin']['plugincreator']['deinstallLink'] = "Si vous voulez simplement désinstaller le plugin, cliquez ici"; 
$this->content->template['message']['plugin']['plugincreator']['checkboxCheck'] = "Oui, je suis sûr de vouloir supprimer ce plugin de façon irrévocable."; 
$this->content->template['message']['plugin']['plugincreator']['rapid_dev_popup_info'] = "Vous pouvez ici assembler un formulaire à l'aide d'éléments de contrôle simples. Sélectionnez un nom pour la variable et l'étiquette, le type d'élément de formulaire et, pour certains types d'éléments, les entrées respectives que l'élément doit avoir et cliquez sur \"Entrer dans la base de données\". Les éléments saisis de cette manière peuvent nécessiter deux rafraîchissements de la page pour devenir visibles.
Les données saisies dans le formulaire créé seront saisies dans un tableau créé automatiquement. Ces données seront ensuite affichées automatiquement dans un tableau situé sous le formulaire \"create new fields\". Si vous ne souhaitez pas que les éléments \"create new fields\" et \"demo data\" soient affichés, supprimez-les du modèle ou désinstallez le plugin \"plugin creator\"."; 

 ?>